- src/_guides/language/effective-dart/design.md
- src/_guides/language/effective-dart/documentation.md
- src/_guides/language/effective-dart/index.md
- src/_guides/language/effective-dart/style.md
- src/_guides/language/effective-dart/usage.md
- src/_guides/language/language-tour.md
- src/_guides/language/sound-dart.md
- src/_guides/language/spec.md
- src/_guides/libraries/create-library-packages.md
- src/_guides/libraries/index.md
- src/_guides/libraries/library-tour.md
- src/_guides/libraries/useful-libraries.md
- src/_guides/packages.md
- src/_tutorials/index.md
- src/codelabs/index.md
- src/community/index.md
- src/get-dart.md
- src/platforms.md
Finished the migration, thanks to:
Translator: @amisare and the dartdoc team he leads.
Migration: @Jin-zz 
Ref: #3
> Finished the migration from dartdoc

- src/_tutorials/language/streams.md
> Fixed streams.md merge conflict.

- src/_guides/language/language-tour.md
- src/_includes/page-footer.html
- src/assets/dash/js/dartpad_picker_main.dart.js
Add the ICP & PSB number to the site and launch the dart.cn!
> launching dart.cn

- src/tools/jetbrains-plugin.md
> Preliminary translation of jetbrains-plugin.md completed.

- src/samples/index.md
> Preliminary translation of sample/index.md completed.

- src/_guides/language/effective-dart/index.md
> Preliminary translation of language.md completed.

- src/_articles/libraries/creating-streams.md
- src/_guides/libraries/c-interop.md
- src/_includes/pub-in-prereleases.html
- src/dart-2.md
- src/get-dart.md
- src/tools/pub/publishing.md
- src/tools/pub/pubspec.md
- src/tools/sdk/archive/index.md
> [sync] 2019/9/29

- src/_assets/image/verified-publisher.svg
- src/_data/side-nav.yml
- src/_includes/banner.html
- src/_tutorials/server/cmdline.md
- src/tools/dart2native.md
- src/tools/pub/publishing.md
- src/tools/pub/verified-publishers.md
ref #123 
新增文档，需要制作成任务 src/tools/pub/verified-publishers.md
> [sync] 2019/10/16

- src/_assets/js/main.js
- src/_assets/js/vendor/jquery-3.4.1.js
- src/tools/sdk/_linux.md
- src/tools/sdk/archive/assets/install.js
> [sync] 2019/11/13

- examples/async_await/analysis_options.yaml
- examples/async_await/bin/async_example.dart
- examples/async_await/bin/futures_intro.dart
- examples/async_await/bin/get_order.dart
- examples/async_await/bin/get_order_sync_bad.dart
- examples/async_await/bin/try_catch.dart
- examples/async_await/dart_test.yaml
- examples/async_await/pubspec.yaml
- examples/async_await/test/async_await_test.dart
- examples/strong/pubspec.yaml
- examples/util/lib/print_matcher.dart
- examples/util/pubspec.yaml
- src/_tutorials/server/get-started.md
- src/codelabs/async-await.md
新增 /codelabs/async-await.md 异步编程：使用 Future 和 async-await
ref: #123
> [sync] 2019/11/30

- src/_guides/language/extension-methods.md
- src/_guides/language/sound-dart.md
- _guides/language/sound-dart.md 完善运行时类型检查的说明
> [sync] 2019/12/15

- Gemfile.lock
> [sync] 2019/12/26

- src/_guides/language/language-tour.md
参考wiki
https://zh.wikipedia.org/zh-hans/%E7%A0%81%E4%BD%8D
> 专有名词 Code Point

- LICENSE
- src/_guides/language/effective-dart/design.md
- src/_guides/language/effective-dart/style.md
- src/_guides/language/effective-dart/usage.md
- src/_guides/language/extension-methods.md
- src/_guides/language/language-tour.md
- src/_includes/page-footer.html
- src/tools/sdk/archive/.gitignore
- src/tools/sdk/archive/out/web/download_archive.dart.js
- src/tools/sdk/dart_sdk_archive/lib/src/version_selector.dart
- 更新了LICENSE 到 4.0
- _guides/language/extension-methods.md 添加了 extension 方法的 YouTube 视频，需要本地化
- _guides/language/language-tour.md 修复了一处代码标签遗漏
- _includes/page-footer.html 更新了 Site License
> [sync] 2020/1/8

- src/tools/pub/publishing.md
翻译完成 publishing.md
完成 Issue #80
> [翻译完成] https://github.com/cfug/dartlang-cn/blob/master/src/tools/pub/publishing.md

- src/_data/side-nav.yml
> Fix Dart 开发语言，目录条目重复

- .travis.yml
- src/_guides/language/evolution.md
- src/get-dart.md
> [sync] 2020/5/14

- examples/misc/lib/effective_dart/style_lib_good.dart
- src/_guides/language/analysis-options.md
- src/_guides/language/effective-dart/style.md
- src/_guides/language/effective-dart/toc.md
- src/_guides/language/effective-dart/usage.md
- src/codelabs/async-await.md
- src/codelabs/iterables.md
> [sync] 2020/5/19

- .travis.yml
- src/_includes/banner.html
- src/get-dart.md
- src/tools/sdk/_linux.md
- src/tools/sdk/_mac.md
- src/tools/sdk/archive/assets/install.js
> sdk install update

- examples/misc/lib/effective_dart/usage_bad.dart
- examples/misc/lib/effective_dart/usage_good.dart
- src/_assets/css/_dash.scss
- src/_guides/language/effective-dart/usage.md
- src/tools/diagnostic-messages.md
> [sync] 2020/7/4

- src/_guides/language/effective-dart/style.md
- src/tools/pub/package-layout.md
> [sync] 2020/7/15

- src/_includes/get-sdk.md
- src/_tutorials/web/get-started.md
- src/get-dart.md
- src/map.html
- src/null-safety/index.md
- src/tools/dart-vm.md
- src/tools/experiment-flags.md
- src/tools/index.md
- src/tools/jetbrains-plugin.md
- src/tools/pub/cmd/pub-get.md
- src/tools/pub/cmd/pub-global.md
- src/tools/pub/environment-variables.md
- src/tools/pub/glossary.md
- src/tools/sdk/index.md
ref #123 
主要是加入了 Flutter 1.20 版之后会包含 Dart SDK 的说明和变更。
> [sync] 2020/7/19

- examples/misc/lib/effective_dart/design_good.dart
- examples/misc/lib/effective_dart/style_good.dart
- examples/misc/lib/effective_dart/usage_bad.dart
- examples/misc/lib/effective_dart/usage_good.dart
- src/_guides/language/effective-dart/design.md
- src/_guides/language/effective-dart/style.md
- src/_guides/language/effective-dart/toc.md
- src/_guides/language/effective-dart/usage.md
- src/web/libraries.md
> [sync] 2020/7/23

- src/null-safety/index.md
> [翻译完成] /src/null-safety/index.md (#209)

- src/null-safety/index.md
> [Fix] Fix Sound null safety page issues

- .travis.yml
- src/_data/pkg-vers.json
- src/_guides/language/evolution.md
- src/_guides/language/spec.md
- src/_includes/get-sdk.md
- src/_tutorials/server/get-started.md
- src/get-dart.md
- src/null-safety/index.md
- src/null-safety/understanding-null-safety/index.md
- src/search.html
- src/tools/diagnostic-messages.md
- src/tools/experiment-flags.md
- src/tools/index.md
- src/tools/jetbrains-plugin.md
- src/tools/sdk/index.md
> [sync] 2020/8/9

- src/_data/side-nav.yml
- src/get-dart.md
- src/null-safety/index.md
> [sync] 2020/8/13

- firebase.json
- src/_assets/css/main.scss
- src/_plugins/code_excerpt_framer.rb
- src/null-safety/index.md
- src/server/c-interop-native-extensions.md
> [sync] 2020/8/28

- examples/strong/lib/animal.dart
- examples/strong/lib/strong_analysis.dart
- src/_guides/language/type-system.md
- src/_tutorials/language/streams.md
> [sync] 2020/8/31

- src/_assets/js/main.js
- src/index.html
Resolves #225, https://github.com/cfug/team/issues/20
> [翻译完成] /src/index.html

- src/index.html
> Fix index page issue

- src/_assets/js/main.js
- src/index.html
* The video uses the mirrored one.
* Improved user experience when the video modal is hiding.
> Change video source to mirror site

- src/_guides/language/effective-dart/usage.md
> Slightly fix effective dart's doc

- .firebaserc
- examples/misc/lib/language_tour/classes/orchestra.dart
- src/_assets/css/_code.scss
- src/_assets/css/_dash.scss
- src/_assets/css/_variables.scss
- src/_assets/css/main.scss
- src/_guides/language/language-tour.md
- src/_includes/navigation-main.html
- src/_includes/navigation-side.html
- src/assets/dash/js/dartpad_picker_main.dart.js
- src/tools/pub/pubspec.md
- tool/dartpad_picker/web/dartpad_picker_main.dart
> [sync] 2020/10/9

- examples/misc/test/language_tour/basic_test.dart
- src/_guides/language/effective-dart/style.md
- src/_guides/language/language-tour.md
- src/null-safety/index.md
- src/tools/sdk/_mac.md
> [sync] 2020/10/16

- src/null-safety/unsound-null-safety.md
> [完成翻译] src/null-safety/unsound-null-safety.md

- src/null-safety/faq.md
> [完成翻译] src/null-safety/faq.md

- src/null-safety/migration-guide.md
> [完成翻译] src/null-safety/migration-guide.md

- src/_includes/gtags.html
- src/_includes/head.html
related work:
https://github.com/cfug/team/issues/14
> Install GTM Code

- src/tools/pub/cmd/pub-global.md
> fix spelling errors in translation

- src/tools/sdk/archive/index.md
- src/tools/sdk/dart_sdk_archive/download_archive.dart_cn.js
- src/tools/sdk/dart_sdk_archive/lib/src/version_selector.dart
fixes: https://github.com/cfug/team/issues/28
> fix: 替换 dart sdk 镜像链接 url

- src/null-safety/understanding-null-safety/index.md
> Update content in understanding null safety

- src/_guides/language/type-system.md
1. 在英文文档中已经去除一些过渡性的说明.
2. 页面中重复的文字及相同链接的不同文字描述也影响阅读.
> sync: type-system

- src/null-safety/faq.md
- src/null-safety/index.md
- src/null-safety/migration-guide.md
- src/null-safety/understanding-null-safety/index.md
- src/null-safety/unsound-null-safety.md
- `您` -> `你`
- 补充了部分未翻译的内容
- 调整了部分语句的细节
> [内容更新] 空安全系列内容调整

- src/null-safety/understanding-null-safety/index.md
> [内容更新] src/null-safety/understanding-null-safety/index.md

- README.md
- null_safety_examples/analysis/pubspec.yaml
- null_safety_examples/analysis_alt/pubspec.yaml
- null_safety_examples/analysis_effective_dart/pubspec.yaml
- null_safety_examples/async_await/pubspec.yaml
- null_safety_examples/basics/pubspec.yaml
- null_safety_examples/create_libraries/pubspec.yaml
- null_safety_examples/extension_methods/pubspec.yaml
- null_safety_examples/fetch_data/pubspec.yaml
- null_safety_examples/html/pubspec.yaml
- null_safety_examples/iterables/pubspec.yaml
- null_safety_examples/misc/pubspec.yaml
- null_safety_examples/null_safety_codelab/pubspec.yaml
- null_safety_examples/util/pubspec.yaml
- pubspec.yaml
- src/_data/side-nav.yml
- src/_guides/language/analysis-options.md
- src/_guides/packages.md
- src/null-safety/faq.md
- src/null-safety/understanding-null-safety/index.md
- src/tools/dart-create.md
- src/tools/dart-tool.md
- src/tools/linter-rules.md
- src/tools/pub/cmd/pub-uploader.md
- src/tools/webdev.md
- src/web/deployment.md
- tool/pubspec.yaml
> [sync] 2021/6/27

- src/_guides/language/language-tour.md
- src/_guides/libraries/library-tour.md
- src/codelabs/dart-cheatsheet.md
Fixes: #309 
Fixes: #267 
Fixes: #258
> issue fixes

- src/_guides/libraries/library-tour.md
> [内容修订] src/guides/libraries/library-tour.md

- src/_guides/language/effective-dart/design.md
> [内容修订] src/guides/language/effective-dart/design.md

- .github/workflows/build.yml
- examples/async_await/pubspec.yaml
- examples/create_libraries/pubspec.yaml
- examples/extension_methods/pubspec.yaml
- examples/fetch_data/pubspec.yaml
- examples/futures/pubspec.yaml
- examples/html/pubspec.yaml
- examples/iterables/pubspec.yaml
- examples/misc/pubspec.yaml
- examples/null_safety_codelab/pubspec.yaml
- examples/type_system/pubspec.yaml
- examples/util/pubspec.yaml
- src/_guides/libraries/private-files.md
- src/_guides/libraries/writing-package-pages.md
- src/_guides/packages.md
- src/_includes/packages-dir.html
- src/_tutorials/libraries/shared-pkgs.md
- src/_tutorials/server/cmdline.md
- src/get-dart/dart_sdk_archive/pubspec.yaml
- src/get-dart/sdk_builds.dart/pubspec.yaml
- src/tools/pub/cmd/pub-downgrade.md
- src/tools/pub/cmd/pub-get.md
- src/tools/pub/cmd/pub-upgrade.md
- src/tools/pub/glossary.md
- src/tools/pub/package-layout.md
- src/tools/pub/versioning.md
> [sync] 2021/11/02

- src/_tutorials/web/get-started.md
> [完成翻译] src/_tutorials/web/get-started.md

- .github/pull_request_template.md
- examples/type_system/analyzer-results-beta.txt
- firebase.json
- src/_guides/language/evolution.md
- src/_guides/language/language-tour.md
- src/_guides/whats-new.md
> [sync] 2021/12/24

- .github/PULL_REQUEST_TEMPLATE.md
- .github/pull_request_template.md
> Fix pull request template issue with non-case-sensitive systems

- src/_guides/language/concurrency/index.md
> [完成翻译] src/_guides/language/concurrency/index.md

- src/_guides/language/concurrency/index.md
> Minor updates

- _config.yml
- examples/analysis_options.yaml
- firebase.json
- src/_guides/language/analysis-options.md
- src/_guides/language/effective-dart/style.md
- src/_guides/language/extension-methods.md
- src/_tutorials/server/cmdline.md
- src/faq.md
- src/null-safety/faq.md
- src/null-safety/index.md
- tool/before-release.sh
- tool/dartpad_picker/analysis_options.yaml
> [sync] 2022/1/17

- .github/workflows/build.yml
- src/_tutorials/web/get-started.md
- src/tools/index.md
- tool/translator/build.sh
rebase the commit about ci-related fixes recently.
> [CI] deploy fixes

- src/codelabs/dart-cheatsheet.md
> [内容修订] src/codelabs/dart-cheatsheet.md

- CODEOWNERS
Automatically request @cfug/localization for review with PRs.
> [Infra] 🔒️ Add CODEOWNERS

- tool/translator/build.sh
- tool/translator/package.json
ref: https://github.com/cfug/team/issues/30
> fix: 生成单中文翻译结果，以验证 SEO 效果

- src/server/index.md
- src/tools/build_runner.md
- src/tools/index.md
- src/tools/pub/cmd/index.md
> fix: replace : to br

- src/_guides/language/effective-dart/design.md
- src/_guides/language/language-tour.md
- src/codelabs/dart-cheatsheet.md
Fix #327 #331 #371 #372.
修复多篇文档错漏问题。
> [内容修订] 修复多篇文档错漏问题

- src/null-safety/migration-guide.md
Fix #374 
主要对页面中因为文档同步 Git 自动 merge 英文而产生的中文未更新的问题进行修复。
> Sync issue fixes.

- .github/workflows/codeql-analysis.yml
- .github/workflows/scorecards-analysis.yml
- src/_data/linter_rules.json
- src/_data/side-nav.yml
- src/_guides/libraries/objective-c-interop.md
- src/tools/dart2js.md
- src/tools/pub/package-layout.md
ref #123 
新增文档:
- 与 OC 互调 src/_guides/libraries/objective-c-interop.md
> [sync] 2022/08/03

- src/get-dart/archive/_sdk-terms.md
Fix #378
禁用匿名分析的命令修订为--disable-analytics
> [内容修订] src/get-dart/archive/_sdk-terms.md

- src/_guides/language/analysis-options.md
> [完成翻译] src/_guides/language/analysis-options.md

- .github/workflows/codeql-analysis.yml
- .github/workflows/scorecards-analysis.yml
- Dockerfile
- examples/misc/lib/effective_dart/design_bad.dart
- examples/misc/lib/effective_dart/design_good.dart
- src/_guides/language/effective-dart/design.md
- src/_guides/libraries/_dart-html-tour.md
- src/_guides/libraries/_dart-io-tour.md
- src/_includes/get-sdk.md
- src/_sass/components/_banner.scss
- src/_sass/components/_search.scss
- src/_sass/components/_sidebar.scss
- src/_sass/components/_toc.scss
- src/_sass/main.scss
- src/get-dart/archive/index.md
- src/get-dart/index.md
- src/tools/jetbrains-plugin.md
ref #123 
没有什么具体的更新，但是修复了下载页面的链接和 js 引用。
> [sync] 2022/10/17

- src/_guides/language/language-tour.md
Credits to: @BodhiSun
Fixes: #397
> Update Final and Const.

- src/_guides/language/language-tour.md
Credits to: @BodhiSun
Fixes: #400 
根据建议将较为口语化的文字修改为更准确的用词。
> [内容修订] src/_guides/language/language-tour.md

- src/_guides/language/effective-dart/design.md
> [内容修订] src/_guides/language/effective-dart/design.md

- src/_guides/language/effective-dart/style.md
> [内容修订] src/_guides/language/effective-dart/style.md

- src/_guides/language/effective-dart/index.md
> [内容修订] src/_guides/language/effective-dart/index.md

- src/_guides/language/effective-dart/design.md
- src/_guides/language/effective-dart/style.md
- src/_guides/language/effective-dart/usage.md
- src/_guides/language/type-system.md
- src/_guides/libraries/library-tour.md
- src/_guides/libraries/useful-libraries.md
- src/_guides/packages.md
- src/codelabs/dart-cheatsheet.md
- src/samples/index.md
- src/tools/index.md
> [完成翻译] src/samples/index.md

- src/_guides/language/effective-dart/documentation.md
> [内容修订] src/_guides/language/effective-dart/documentation.md

- src/_guides/language/effective-dart/usage.md
> [内容修订] src/_guides/language/effective-dart/usage.md

- src/get-dart/archive/assets/download_archive.dart.js
- tool/get-dart/archive/compile.sh
- tool/get-dart/dart_sdk_archive/lib/src/version_selector.dart
- tool/get-dart/sdk_builds.dart/lib/src/dart_downloads.dart
> [sync] 2023/03/03

- src/_guides/language/language-tour.md
- src/codelabs/dart-cheatsheet.md
- src/tools/pub/cmd/index.md
修改多处重定向的地址为实际地址，帮助构建全站时进行链接检查。
> [内容修订] Fix redirected links

- src/language/variables.md
> [内容修订] https://dart.cn/language/variables

- tool/get-dart/sdk_builds.dart/lib/src/dart_downloads.dart
Using storage-apis.dart.cn to avoid CROS issue.
> Fix dart-sdk-downloads.

- src/content/assets/js/get-dart/download_archive.dart.js
- tool/get-dart/dart_sdk_archive/lib/src/version_selector.dart
- tool/get-dart/sdk_builds.dart/lib/src/dart_downloads.dart
Fixed https://github.com/cfug/dart.cn/issues/430 (PR: https://github.com/cfug/dart.cn/pull/448)
- Fixed to correct Dart SDK download link.
- Update download_archive.dart.js.
> Fix: Dart archive page CROS and downloads

- src/_includes/head.html
> Update: cdn.staticfile.org -> cdn.staticfile.net

- src/content/interop/c-interop.md
- src/content/tools/index.md
| ❌ Before | ✅ After |  
| --- | --- |  
| ![before](https://github.com/cfug/dart.cn/assets/32262985/fef28e92-26da-44bc-8e66-c46a65b872b2) | ![after](https://github.com/cfug/dart.cn/assets/32262985/7ed908a0-c042-44b0-92a6-f5278ab30f19) |
> Fix: Table formatting

- src/content/terms.md
> [内容修订] src/content/terms.md

- src/_11ty/plugins/markdown.js
无关联 issues。
| 提示项 | 预览 | 
| --- | --- |
| note |  ![note](https://github.com/cfug/dart.cn/assets/32262985/6d85dfe2-884e-424e-b2f1-876ccb8e326e) |
| flutter-note | ![flutter-note](https://github.com/cfug/dart.cn/assets/32262985/5de37581-3ab1-4910-93be-a2048427d251) |
| version-note | ![version-note](https://github.com/cfug/dart.cn/assets/32262985/043786be-ecb8-4e43-94a6-2f45510124c2) |
| tip | ![tip](https://github.com/cfug/dart.cn/assets/32262985/6b2fa700-9e6d-4374-8e31-5e1a49c7f2f3) |
| warning | ![warning](https://github.com/cfug/dart.cn/assets/32262985/55476530-547b-4436-a7c9-707602a52de5) |
| important | ![important](https://github.com/cfug/dart.cn/assets/32262985/558f9427-6660-423e-aff1-c30e01b3cae9) |
> [完成翻译] src/_11ty/plugins/markdown.js - Alert (Aside)

- src/_includes/head.html
ref https://github.com/cfug/team/issues/57
请先合并 https://github.com/cfug/files.flutter-io.cn/pull/6 ，并等待资源有效后再合并当前 PR。
> Update: cdn.staticfile.net -> files.flutter-io.cn

- tool/translator/gulpfile.js
https://github.com/cfug/flutter.cn/pull/1479
> Fix: translator - gulpfile.js

- src/content/language/variables.md
Fix #479.
有关final和const值修改的描述，语义有误，已更正。
> [内容修订] src/content/language/variables.md

- .github/workflows/build.yml
https://github.com/cfug/flutter.cn/pull/1518
> Fix: Page last updated

- src/content/404.html
Fixed https://github.com/cfug/team/issues/69
> Fix: Try requesting the URL with the .html suffix

- src/content/language/comments.md
> [完成翻译] src/content/language/comments.md
